db.movies.find({})
db.movies.insertMany([{}])
db.movies.find({}).pretty()
db.movies.find({rating:{$gt:8}}).pretty()
db.movies.find({rating:{$gte:8}}).pretty()
db.movies.find({},{name:1,rating:1}).pretty()
db.movies.find({},{name:0,rating:0}).pretty()
db.movies.find({},{id_:0,name:1,rating:1}).pretty()
db.movies.find({},{id_:0,name:0,rating:0}).pretty()
db.movies.find({}).sort({rating:1}).pretty()
db.movies.find({}).sort({rating:-1}).pretty()
db.movies.find({}).sort({rating:-1}).limit(2).pretty()
db.movies.find({}).sort({rating:-1}).skip(2).pretty()
db.movies.updateMany({},{$set:{language:"french"}})
db.movies.updateOne({name:"dada"},{$set:{language:"french"}})
db.movies.updateOne({name:"dada"},{$set:{rating:9}})

